#!/usr/bin/env python
import autowaf
import os

# Version of this package (even if built as a child)
EUGENE_VERSION = '0.0.0'

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
# Version history:
#   0.0.0 = 0,0,0
EUGENE_LIB_VERSION = '0.0.0'

# Variables for 'waf dist'
APPNAME = 'eugene'
VERSION = EUGENE_VERSION

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	autowaf.set_options(opt)

def configure(conf):
	autowaf.configure(conf)
	autowaf.check_tool(conf, 'compiler_cxx')
	autowaf.check_pkg(conf, 'flowcanvas', destvar='FLOWCANVAS', vnum='0.5.1', mandatory=True)
	autowaf.check_pkg(conf, 'glibmm-2.4', destvar='GLIBMM', vnum='2.14.0', mandatory=True)
	autowaf.check_pkg(conf, 'gthread-2.0', destvar='GTHREAD', vnum='2.16.0', mandatory=True)
	autowaf.check_pkg(conf, 'gtkmm-2.4', destvar='GTKMM', vnum='2.11.12', mandatory=True)
	autowaf.check_pkg(conf, 'libglademm-2.4', destvar='GLADEMM', vnum='2.6.0', mandatory=True)
	autowaf.check_pkg(conf, 'libgnomecanvasmm-2.6', destvar='GNOMECANVASMM', mandatory=True)
	
	conf.env.append_value('CXXFLAGS', '-fopenmp')
	conf.env.append_value('LINKFLAGS', '-fopenmp')
	print conf.env
	conf.define('DATA_DIR', os.path.normpath(conf.env['PREFIX'] + '/share/eugene'))
	conf.write_config_header('config.h')
	
	autowaf.print_summary(conf)

def build(bld):
	# Headers
	#install_files('INCLUDEDIR', 'eugene', 'eugene/*.h')
	#install_files('INCLUDEDIR', 'eugene', 'eugene/*.hpp')
	
	# Pkgconfig file
	autowaf.build_pc(bld, 'EUGENE', EUGENE_VERSION, 'GLIBMM GTHREAD')
	
	# Library
	obj = bld.create_obj('cpp', 'shlib')
	obj.source = '''
		src/LABS.cpp
		src/Sphere.cpp
		src/TSP.cpp
	'''
	obj.includes = ['.']
	obj.name     = 'libeugene'
	obj.target   = 'eugene'
	obj.uselib   = 'GLIBMM GTHREAD'
	obj.vnum     = EUGENE_LIB_VERSION
	obj.inst_dir = bld.env()['LIBDIRNAME']
	
	# Console app
	prog = bld.create_obj('cpp', 'program')
	prog.source       = 'src/eugene.cpp'
	obj.includes      = ['.']
	prog.uselib_local = 'libeugene'
	prog.target       = 'src/eugene'
	prog.inst_dir     = bld.env()['BINDIRNAME']

	# GUI app
	prog = bld.create_obj('cpp', 'program')
	prog.source = '''
		gui/MainWindow.cpp
		gui/TSPCanvas.cpp
		gui/eugene_tsp_gui.cpp
	'''
	obj.includes      = ['.']
	prog.uselib_local = 'libeugene'
	prog.uselib       = 'GTKMM GLADEMM GTHREAD GNOMECANVASMM FLOWCANVAS'
	prog.target       = 'gui/eugene_tsp_gui'
	prog.inst_dir     = bld.env()['BINDIRNAME']
	
	install_files('PREFIX', 'share/eugene', 'gui/eugene_tsp_gui.glade')
	
def shutdown():
	autowaf.shutdown()

