#!/usr/bin/env python
import Params

# Variables for 'waf dist'
VERSION = '0.0.0'
APPNAME = 'redlandmm'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cxx')

def configure(conf):
	if not conf.env['HAVE_GLIBMM']:
		conf.check_pkg('glibmm-2.4', destvar='GLIBMM', vnum='2.16.0', mandatory=True)
	if not conf.env['HAVE_GTHREAD']:
		conf.check_pkg('gthread-2.0', destvar='GTHREAD', vnum='2.16.0', mandatory=True)
	if not conf.env['HAVE_REDLAND']:
		conf.check_pkg('redland', destvar='REDLAND', vnum='1.0.8', mandatory=True)
	if not conf.env['CXX']:
		conf.check_tool('compiler_cxx')

def build(bld):
	# Headers (redlandmm)
	install_files('PREFIX', 'include/redlandmm', 'redlandmm/*.hpp')
	
	# Library (src)
	obj = bld.create_obj('cpp', 'shlib')
	obj.source = '''
		src/Model.cpp
		src/Namespaces.cpp
		src/Node.cpp
		src/Query.cpp
		src/World.cpp
	'''
	obj.includes = '..'
	obj.name     = 'libredlandmm'
	obj.target   = 'redlandmm'
	obj.uselib   = 'REDLAND GLIBMM GTHREAD'
	obj.vnum     = '1.0.0'

	# Test (test)
	obj = bld.create_obj('cpp', 'program')
	obj.source       = 'tests/rdf_test.cpp'
	obj.includes     = '..'
	obj.uselib_local = 'libredlandmm'
	obj.target       = 'tests/rdf_test'
	obj.inst_var     = 0
