#!/usr/bin/env python
import Params
import autowaf

# Version of this package (even if built as a child)
FLOWCANVAS_VERSION = '0.5.2'

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
# Version history:
#   0.4.0 = 0,0,0
#   0.5.0 = 1,0,0
#   0.5.1 = 2,0,0
FLOWCANVAS_LIB_VERSION = '2.0.0'

# Variables for 'waf dist'
APPNAME = 'flowcanvas'
VERSION = FLOWCANVAS_VERSION

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cxx')
	opt.tool_options('compiler_cc')

def configure(conf):
	if not conf.env['CC']:
		conf.check_tool('compiler_cc')
	if not conf.env['CXX']:
		conf.check_tool('compiler_cxx')
	if not conf.env['AGRAPH']:
		conf.check_pkg('libgvc', destvar='AGRAPH', vnum='2.8', mandatory=False)
	if not conf.env['GLIBMM']:
		conf.check_pkg('gtkmm-2.4', destvar='GLIBMM', vnum='2.10.0', mandatory=True)
	if not conf.env['GNOMECANVASMM']:
		conf.check_pkg('libgnomecanvasmm-2.6', destvar='GNOMECANVASMM', vnum='2.6.0', mandatory=True)

	conf.check_header('boost/shared_ptr.hpp')
	conf.check_header('boost/weak_ptr.hpp')
	conf.write_config_header('waf-config.h')
	conf.env.append_value('CXXFLAGS', '-DCONFIG_H_PATH=\\\"waf-config.h\\\"')

def build(bld):
	# Headers
	install_files('PREFIX', 'include/flowcanvas', 'flowcanvas/*.hpp')
	
	# Pkgconfig file
	autowaf.build_pc(bld, 'FLOWCANVAS', FLOWCANVAS_VERSION, 'AGRAPH GLIBMM GNOMECANVASMM')
	
	# Library
	obj = bld.create_obj('cpp', 'shlib')
	obj.source = '''
		src/Canvas.cpp 
		src/Connectable.cpp 
		src/Connection.cpp 
		src/Ellipse.cpp 
		src/Item.cpp 
		src/Module.cpp 
		src/Port.cpp
	'''
	obj.includes = '..'
	obj.name     = 'libflowcanvas'
	obj.target   = 'flowcanvas'
	obj.uselib   = 'GTKMM GNOMECANVASMM AGRAPH'
	obj.vnum     = FLOWCANVAS_LIB_VERSION
	
	# Documentation
	autowaf.build_dox(bld, 'FLOWCANVAS', FLOWCANVAS_VERSION, srcdir, blddir)
	install_files('PREFIX', 'share/doc/flowcanvas', blddir + '/default/doc/html/*')

