#!/usr/bin/env python
import Params

# Variables for 'waf dist'
VERSION='0.0.1'
APPNAME='evoral'

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cxx')

def configure(conf):
	if not conf.env['GLIBMM']:
		conf.check_pkg('glibmm-2.4', destvar='GLIBMM', vnum='2.16.0', mandatory=True)
	if not conf.env['GTHREAD']:
		conf.check_pkg('gthread-2.0', destvar='GTHREAD', vnum='2.16.0', mandatory=True)
	if not conf.env['CXX']:
		conf.check_tool('compiler_cxx')

def build(build):
	build.add_subdirs('src test')
	install_files('PREFIX', 'include/evoral', 'evoral/*.hpp')

