#!/usr/bin/env python

def build(bld):
	obj = bld.create_obj('cpp', 'program')
	obj.source='''
		sequence.cpp
	'''
	obj.includes     = '..'
	obj.uselib_local = 'libevoral'
	obj.target       = 'sequence'
	obj.inst_var     = 0
	
