#!/usr/bin/env python
import Params
import autowaf

def build(bld):
	core_source = '''
		Action.cpp
		ActionFactory.cpp
		Edge.cpp
		Engine.cpp
		Evolver.cpp
		JackDriver.cpp
		LearnRequest.cpp
		Loader.cpp
		Machine.cpp
		MachineBuilder.cpp
		MidiAction.cpp
		Mutation.cpp
		Node.cpp
		Problem.cpp
		RaulJackDriver.cpp
		Recorder.cpp
		SMFDriver.cpp
	'''

	obj = bld.create_obj('cpp', 'shlib')
	obj.source = core_source
	obj.includes     = ['.', '..']
	obj.name         = 'libmachina_engine'
	obj.target       = 'machina_engine'
	core_libs = 'GLIBMM GTHREAD RAUL REDLANDMM JACK EUGENE'
	autowaf.use_lib(bld, obj, core_libs)
	
