#!/usr/bin/env python

def build(bld):
	obj = bld.create_obj('cpp', 'shlib')
	obj.source='''
		Control.cpp
		ControlList.cpp
		ControlSet.cpp
		Curve.cpp
		Event.cpp
		MIDIEvent.cpp
		Note.cpp
		SMF.cpp
		SMFReader.cpp
		Sequence.cpp
	'''
	obj.includes = '..'
	obj.name     = 'libevoral'
	obj.target   = 'evoral'
	obj.uselib   = 'GLIBMM GTHREAD'
	obj.vnum     = '0.0.0'
