#!/usr/bin/env python
import Params
import autowaf

# Version of this package (even if built as a child)
LV2CORE_VERSION = '2.0'

# Variables for 'waf dist'
VERSION = '2.0'
VERSION = LV2CORE_VERSION

# Mandatory variables
srcdir = '.'
blddir = 'build'

def set_options(opt):
    opt.add_option('--bundle-dir', type='string', dest='bundle_dir',
			help="Bundle install directory [Default: PREFIX/lib/lv2]")

def configure(conf):
	autowaf.configure(conf)

def build(bld):
	# Header
	install_files('PREFIX', 'include', 'lv2.h')
	
	# Pkgconfig file
	autowaf.build_pc(bld, 'LV2CORE', LV2CORE_VERSION, [])

	# Bundle (data)
	dir = Params.g_options.bundle_dir
	if dir == None:
		dir = bld.env()['PREFIX'] + 'lib/lv2'
	install_files(dir, 'lv2core.lv2', 'lv2core.lv2/lv2.ttl lv2core.lv2/manifest.ttl')

